version: "3"
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/postgres?user=${POSTGRES_USER:-postgres}&password=${POSTGRES_PASSWORD:-postgres} -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ${PWD}/server/migrations:/flyway/sql
    depends_on:
      - db
    networks:
      - back

  db:
    container_name: postgres_container
    image: postgres:13.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - back
    restart: unless-stopped

  backend:
    restart: always
    container_name: backend
    build: ./server
    expose:
      - 5000
    volumes:
      - ./server:/usr/src/app
    networks:
      - back
      - front
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      FLASK_APP: api.py
      FLASK_DEBUG: 1
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - front
    depends_on:
      - backend

networks:
  back:
  front:

volumes:
  postgres:
